---
managed_device:
  junos-default:
  - 10.85.192.14
  - 10.85.192.15
  - 10.85.192.16
  - 10.85.192.17
  - 10.85.192.19
  - 10.85.192.20
logical_device:
  spine:
    name: terra-spine  # reuse for interface-map name
    device_profile_id: Juniper_QFX10002-36Q_Junos
    panels:
    - rows: 2
      columns: 18
      port_groups:
      - port_count: 36
        port_speed: 40G
        port_roles: [ 'leaf', 'generic']
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: et-0/0/
      phy_first_port: 0
      count: 36
    device_allocation:
      spine1: EK069
      spine2: FQ824
  border-leaf:
    name: terra-border-leaf
    device_profile_id: Juniper_QFX5120-48Y_Junos
    panels:
    - rows: 2
      columns: 28
      port_groups:
      - port_count: 24
        port_speed: 10G
        port_roles: [ 'access', 'generic']
      - port_count: 24
        port_speed: 25G
        port_roles: [ 'access', 'generic']
      - port_count: 8
        port_speed: 40G
        port_roles: [ 'spine', 'generic']
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: xe-0/0/
      phy_first_port: 0
      count: 24
    - ld_panel: 1
      ld_first_port: 25
      phy_prefix: et-0/0/
      phy_first_port: 24
      count: 32
    device_allocation:
      terra_border_001_leaf1: XH3119430106
      terra_border_001_leaf2: XH3119430153
  server-leaf:
    name: terra-server-leaf
    device_profile_id: Juniper_QFX5100-48S_Junos
    panels:
    - rows: 2
      columns: 27
      port_groups:
      - port_count: 48
        port_speed: 10G
        port_roles: [ 'access', 'generic']
      - port_count: 6
        port_speed: 40G
        port_roles: [ 'spine', 'generic']
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: xe-0/0/
      phy_first_port: 0
      count: 48
    - ld_panel: 1
      ld_first_port: 49
      phy_prefix: et-0/0/
      phy_first_port: 48
      count: 6
    device_allocation:
      terra_server_001_leaf1: TA3717380176
      terra_server_001_leaf2: TA3717380282
resource:
  ipv4_pool:
    terra-loop:
      name: terra-loop
      subnets:
      - network: "10.0.0.0/24"
    terra-fabric:
      name: terra-fabric
      subnets:
      - network: "10.0.1.0/24"
  asn:
    terra-asn:
      name: terra-asn
      ranges:
      - first: 4200000000
        last: 4200001000

    


