---
managed_device:
  junos-default:
  - 10.85.192.14
  - 10.85.192.15
  - 10.85.192.16
  - 10.85.192.17
  - 10.85.192.19
  - 10.85.192.20
logical_device:
  spine:
    name: terra-spine  # reuse for interface-map name
    blueprint: terra
    panels:
    - rows: 2
      columns: 18
      port_groups:
      - port_count: 36
        port_speed: 40G
        port_roles: [ 'leaf', 'generic']
    device_allocation:
      spine1: EK069
      spine2: FQ824
  border-leaf:
    name: terra-border-leaf
    blueprint: terra
    panels:
    - rows: 2
      columns: 28
      port_groups:
      - port_count: 24
        port_speed: 10G
        port_roles: [ 'access', 'generic']
      - port_count: 24
        port_speed: 25G
        port_roles: [ 'access', 'generic']
      - port_count: 8
        port_speed: 40G
        port_roles: [ 'spine', 'generic']
    device_allocation:
      terra_border_001_leaf1: XH3119430106
      terra_border_001_leaf2: XH3119430153
  server-leaf:
    name: terra-server-leaf
    blueprint: terra
    panels:
    - rows: 2
      columns: 27
      port_groups:
      - port_count: 48
        port_speed: 10G
        port_roles: [ 'access', 'generic']
      - port_count: 6
        port_speed: 40G
        port_roles: [ 'spine', 'generic']
    device_allocation:
      terra_server_001_leaf1: TA3717380176
      terra_server_001_leaf2: TA3717380282
interface_map:
  spine:
    name: terra-spine  # reuse for interface-map name
    logical_device: spine
    device_profile_id: Juniper_QFX10002-36Q_Junos
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: et-0/0/
      phy_first_port: 0
      count: 36
  border-leaf:
    name: terra-border-leaf
    logical_device: border-leaf
    device_profile_id: Juniper_QFX5120-48Y_Junos
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: xe-0/0/
      phy_first_port: 0
      count: 24
    - ld_panel: 1
      ld_first_port: 25
      phy_prefix: et-0/0/
      phy_first_port: 24
      count: 32
  server-leaf:
    name: terra-server-leaf
    logical_device: server-leaf
    device_profile_id: Juniper_QFX5100-48S_Junos
    device_mapping:
    - ld_panel: 1
      ld_first_port: 1
      phy_prefix: xe-0/0/
      phy_first_port: 0
      count: 48
    - ld_panel: 1
      ld_first_port: 49
      phy_prefix: et-0/0/
      phy_first_port: 48
      count: 6
resource:
  asn_pool:
    terra-asn:  # name
    - first: 4200000000  # ranges
      last: 4200001000
  vni_pool:
    terra:
    - first: 200000
      last: 600000
  integer_pool:
    test:
    - first: 1000
      last: 2000
  ipv4_pool:
    terra-loop:
    - 10.0.0.0/24  # subnets
    terra-fabric:
    - 10.0.1.0/24
  ipv6_pool:
    terra-fabric:  # subnets
    - 2001:db8::/32
rack_type:
  server-rack:
    name: terra-server
    description: server rack
    fabric_connectivity_design: l3clos
    leaf_switches:
    - logical_device: server-leaf
      spine_link_count: 1
      spine_link_speed: 40G
      redundancy_protocol: esi
  border-rack:
    name: terra-border
    fabric_connectivity_design: l3clos
    description: border rack
    leaf_switches:
    - logical_device: border-leaf
      spine_link_count: 1
      spine_link_speed: 40G
      redundancy_protocol: esi
template:
  template-terra:
    name: terra-template
    asn_allocation_scheme: unique
    overlay_control_protocol: evpn
    spine:
      logical_device: spine
      count: 2
    racks:
      server-rack: 1
      border-rack: 1
blueprint:
  terra:
    name: terra
    template_name: template-terra
    asn_pools:
      spine_asns:
      - terra-asn # from resource
      leaf_asns:
      - terra-asn
    ipv4_pools:
      spine_loopback_ips:
      - terra-loop
      leaf_loopback_ips:
      - terra-loop
      spine_leaf_link_ips:
      - terra-fabric
    routing_zones:
      vrf-blue:
        vlan_id: 4001
        vni: 504001
        dhcp_servers: ["192.168.100.10", "192.168.200.10"]





